apiVersion: v1
kind: Service
metadata:
  name: kapsa-operator-metrics
  namespace: kapsa-system
  labels:
    app.kubernetes.io/name: kapsa-operator
    app.kubernetes.io/component: operator
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: kapsa-operator
