{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kapsa-operator
  labels:
    app.kubernetes.io/name: kapsa-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  # Kapsa CRDs
  - apiGroups:
      - kapsa.io
    resources:
      - projects
      - projects/status
      - environments
      - environments/status
      - domainpools
      - domainpools/status
      - registries
      - registries/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # kpack resources
  - apiGroups:
      - kpack.io
    resources:
      - images
      - images/status
      - builds
      - builds/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # Kubernetes core resources
  - apiGroups:
      - ""
    resources:
      - namespaces
      - serviceaccounts
      - services
      - configmaps
      - secrets
      - events
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
      - ingresses/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # HorizontalPodAutoscaler
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # cert-manager resources
  - apiGroups:
      - cert-manager.io
    resources:
      - certificates
      - certificaterequests
      - issuers
      - clusterissuers
    verbs:
      - get
      - list
      - watch

  # RBAC for project namespaces
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # Leases for leader election
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
{{- end }}
