apiVersion: apps/v1
kind: Deployment
metadata:
  name: kapsa-operator
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: kapsa-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: operator
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: kapsa-operator
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kapsa-operator
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: operator
      annotations:
        # Force rolling update on config changes
        checksum/config: {{ include (print $.Template.BasePath "/operator/configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ .Values.operator.serviceAccount.name }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.securityContext.operator | nindent 8 }}
      containers:
        - name: operator
          image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          env:
            - name: KAPSA_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KAPSA_LOG_LEVEL
              value: {{ .Values.operator.logging.level }}
            - name: KAPSA_LOG_FORMAT
              value: {{ .Values.operator.logging.format }}
            - name: KAPSA_DEFAULT_POLL_INTERVAL
              value: "{{ .Values.operator.reconciliation.defaultPollInterval }}"
            - name: KAPSA_RESYNC_PERIOD
              value: "{{ .Values.operator.reconciliation.resyncPeriod }}"
            {{- if .Values.operator.metrics.enabled }}
            - name: KAPSA_METRICS_ENABLED
              value: "true"
            - name: KAPSA_METRICS_PORT
              value: "{{ .Values.operator.metrics.port }}"
            {{- end }}
          ports:
            {{- if .Values.operator.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.operator.metrics.port }}
              protocol: TCP
            {{- end }}
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
          {{- if .Values.operator.metrics.enabled }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.operator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
