apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: domainpools.kapsa-project.io
  annotations:
    helm.sh/resource-policy: keep
spec:
  group: kapsa-project.io
  names:
    kind: DomainPool
    listKind: DomainPoolList
    plural: domainpools
    singular: domainpool
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - baseDomains
                - certManager
              properties:
                baseDomains:
                  type: array
                  description: Available base domains for allocation
                  items:
                    type: string
                  minItems: 1
                certManager:
                  type: object
                  required:
                    - issuerRef
                  properties:
                    issuerRef:
                      type: object
                      required:
                        - name
                        - kind
                      properties:
                        name:
                          type: string
                          description: Name of the cert-manager ClusterIssuer or Issuer
                        kind:
                          type: string
                          enum:
                            - ClusterIssuer
                            - Issuer
                          default: ClusterIssuer
                          description: Type of cert-manager issuer
                allocationPolicy:
                  type: object
                  properties:
                    strategy:
                      type: string
                      enum:
                        - round-robin
                        - random
                        - least-used
                      default: round-robin
                    reservedSubdomains:
                      type: array
                      description: Subdomains that cannot be allocated
                      items:
                        type: string
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    required:
                      - type
                      - status
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                allocations:
                  type: array
                  items:
                    type: object
                    properties:
                      subdomain:
                        type: string
                      baseDomain:
                        type: string
                      project:
                        type: string
                      environment:
                        type: string
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Base Domains
          type: string
          jsonPath: .spec.baseDomains[0]
        - name: Issuer
          type: string
          jsonPath: .spec.certManager.issuerRef.name
        - name: Ready
          type: string
          jsonPath: .status.conditions[?(@.type=="Ready")].status
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
