{{- if .Values.crds.install }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: projects.kapsa-project.io
  annotations:
    {{- if .Values.crds.keep }}
    helm.sh/resource-policy: keep
    {{- end }}
spec:
  group: kapsa-project.io
  names:
    kind: Project
    listKind: ProjectList
    plural: projects
    singular: project
    shortNames:
      - proj
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - repository
                - build
                - registry
                - domain
              properties:
                repository:
                  type: object
                  required:
                    - url
                  properties:
                    url:
                      type: string
                      description: Git repository URL
                    branch:
                      type: string
                      description: Default branch
                      default: main
                    pollInterval:
                      type: integer
                      description: Poll interval in seconds
                      default: 300
                      minimum: 60
                    credentials:
                      type: object
                      description: Git credentials reference
                      properties:
                        secretRef:
                          type: object
                          required:
                            - name
                          properties:
                            name:
                              type: string
                            namespace:
                              type: string
                build:
                  type: object
                  required:
                    - strategy
                  properties:
                    strategy:
                      type: string
                      enum:
                        - dockerfile
                        - buildpack
                      description: Build strategy
                    dockerfile:
                      type: string
                      description: Path to Dockerfile (required if strategy=dockerfile)
                    context:
                      type: string
                      description: Build context path
                      default: .
                    args:
                      type: object
                      description: Build arguments
                      additionalProperties:
                        type: string
                    env:
                      type: array
                      description: Build-time environment variables
                      items:
                        type: object
                        required:
                          - name
                          - value
                        properties:
                          name:
                            type: string
                          value:
                            type: string
                registry:
                  type: object
                  required:
                    - name
                    - imageRepository
                  properties:
                    name:
                      type: string
                      description: Reference to Registry CRD
                    imageRepository:
                      type: string
                      description: Image repository path within registry
                domain:
                  type: object
                  required:
                    - subdomain
                    - domainPoolRef
                  properties:
                    subdomain:
                      type: string
                      description: Subdomain for this project
                      pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
                    domainPoolRef:
                      type: string
                      description: Reference to DomainPool CRD
                environments:
                  type: array
                  description: List of permanent environments
                  items:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
                        pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
                      branch:
                        type: string
                      autoSync:
                        type: boolean
                        default: false
                previewEnvironments:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                      default: false
                    ttl:
                      type: string
                      description: Time-to-live for preview environments (e.g., 168h)
                      default: 168h
                    branches:
                      type: object
                      properties:
                        include:
                          type: array
                          items:
                            type: string
                        exclude:
                          type: array
                          items:
                            type: string
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    required:
                      - type
                      - status
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                        enum:
                          - "True"
                          - "False"
                          - Unknown
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                latestCommit:
                  type: string
                latestImage:
                  type: string
                environments:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      ready:
                        type: boolean
                      url:
                        type: string
                      type:
                        type: string
                        enum:
                          - permanent
                          - preview
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Repository
          type: string
          jsonPath: .spec.repository.url
        - name: Ready
          type: string
          jsonPath: .status.conditions[?(@.type=="Ready")].status
        - name: Latest Image
          type: string
          jsonPath: .status.latestImage
          priority: 1
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
{{- end }}
